import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"  
import Header from '@/components/Header'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from "@/components/ui/toaster"
import Footer from '@/components/Footer'
export const metadata: Metadata = {
  title: 'diff.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        <Toaster />
        <div className="absolute inset-0 -z-10 h-full w-full  bg-[linear-gradient(to_right,#0f0f0f_1px,transparent_1px),linear-gradient(to_bottom,#0f0f0f_1px,transparent_1px)] bg-[size:6rem_4rem]">
        <div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_500px_at_50%_200px,#09171f,transparent)]"></div>
        </div>
        </ThemeProvider >
        <Footer />
        </body>
    </html>
  )
}
